jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cue-lang/setup-cue@main
    - run: cue build
    - uses: actions/upload-artifact@v3
      with:
        name: GreenSpaces
        path: output/GreenSpaces

on:
  workflow_call:
