jobs:
  build:
    uses: ./.github/workflows/build.yml

  vet:
    name: cue vet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cue-lang/setup-cue@main
    - run: cue vet --concrete --strict

  fmt:
    name: cue fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cue-lang/setup-cue@main
    - run: cue fmt . ./schema ./GreenSpaces
    - run: git diff --exit-code

  line-length:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        awk '
          BEGIN {
            max = 80
          }
          length() > max {
            print FILENAME ":" FNR " (line length " length() " > " max ")"
            code = 1
          }
          END {
            exit code
          }
        ' **/*.cue

  success:
    needs: [build, vet, fmt, line-length]
    runs-on: ubuntu-latest
    steps:
    - run: true

on:
  pull_request:
    branches: [prīmum]
